name: weather_app  # Add your project name here
description: A weather app built with Flutter.

environment:
  sdk: '>=3.6.0 <4.0.0'  # Ensure compatibility with Dart 3.6 and above

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  http: ^0.13.5
  video_player: ^2.8.2  # Replace with the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons: 
 android: true
 ios: true
 image_path: "assets/logo.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
    - assets/logo.webp
